import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from '@/lib/i18n';
import Page from '@/components/Page';

const Home: NextPage = () => {
  const { t } = useTranslation();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        {t('common:index')}
      </Page>
    </div>
  );
};

export default Home;
